CHANNEL_SECRET = ENV['LINE_CHANNEL_SECRET']

CHANNEL_ACCESS_TOKEN = ENV['LINE_CHANNEL_ACCESS_TOKEN']

USERNAME = ENV['WATSON_USERNAME']
PASSWORD = ENV['WATSON_PASSWORD']
CLUSTER_ID = ENV['WATSON_CLUSTER_ID']
RANKER_ID = ENV['WATSON_RANKER_ID']