LINE_ENDPOINT = 'https://api.line.me'
LINE_CHANNEL_SECRET = ENV['LINE_CHANNEL_SECRET']
LINE_CHANNEL_ACCESS_TOKEN = ENV['LINE_CHANNEL_ACCESS_TOKEN']

WATSON_USERNAME = ENV['WATSON_USERNAME']
WATSON_PASSWORD = ENV['WATSON_PASSWORD']
WATSON_CLUSTER_ID = ENV['WATSON_CLUSTER_ID']
WATSON_RANKER_ID = ENV['WATSON_RANKER_ID']